# Numpy

Numpy is a very efficient numerical processing library. In Python everything is an object. In contrast, Numpy uses primitive numeric types (floats, ints) which makes storing and computation more efficient than in Python.

## Numpy Arrays

In [55]:
import numpy as np

a = np.array([1, 2, 3, 128], dtype=np.int8)
b = np.array([0, .5, 1, 1.5, 2.2222222], dtype=np.float16)

In [56]:
a[0], a[1]

(1, 2)

In [57]:
a[0:]

array([   1,    2,    3, -128], dtype=int8)

In [58]:
a[1:3]

array([2, 3], dtype=int8)

In [59]:
b[[0, 2, -1]] # Multi-indexing

array([0.   , 1.   , 2.223], dtype=float16)

In [60]:
[b[-2], b[-1], b[-3]]

[1.5, 2.223, 1.0]

In [61]:
a.dtype

dtype('int8')

In [62]:
b.dtype

dtype('float16')

### Dimmensions and Shape

In [75]:
A = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
],
[
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]]
)

In [76]:
A.shape

(2, 3, 3)

In [77]:
A.ndim # Number of dimmensions

3

In [78]:
A.size

18

In [79]:
A.dtype

dtype('int64')

### Indexing and Slicing Matrices

In [80]:
A[1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [82]:
A[1][1]

array([6, 5, 4])

In [84]:
A[0,1]

array([4, 5, 6])

In [92]:
A[:2,1:,1:3]

array([[[5, 6],
        [8, 9]],

       [[5, 4],
        [2, 1]]])

### Statistics

In [93]:
b.sum()

5.223

In [94]:
b.mean()

1.045

In [95]:
b.std()

0.7725

In [96]:
b.var()

0.5967

In [97]:
A.sum()

90

In [98]:
A.mean()

5.0

In [99]:
A.std()

2.581988897471611

In [102]:
A.sum(axis=0)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [103]:
A.sum(axis=1)

array([[12, 15, 18],
       [18, 15, 12]])

In [104]:
A.sum(axis=2)

array([[ 6, 15, 24],
       [24, 15,  6]])

In [107]:
A.mean(axis=2)

array([[2., 5., 8.],
       [8., 5., 2.]])

## Numpy Operations

### Broadcasting and Vectorized Operations

In [116]:
c = np.arange(4)

In [109]:
c

array([0, 1, 2, 3])

In [111]:
c + 10 # element wise sum

array([10, 11, 12, 13])

In [117]:
c += 1

In [118]:
c

array([1, 2, 3, 4])

In [122]:
a + c # element wise sum

array([   2,    4,    6, -124])